FROM maven:3.8.3-openjdk-17 AS build
COPY pom.xml /app/
COPY src /app/src
WORKDIR /app/
RUN mvn clean package

FROM amazoncorretto:17-alpine-jdk
COPY --from=build /app/target/*.jar usersapp.jar
ENTRYPOINT ["java","-jar","usersapp.jar"]
